#! /bin/sh

set -e

start() {
       /home/tacman/script/backgroundrb start
}
stop() {
       /home/tacman/script/backgroundrb stop
}
restart() {
        /home/tacman/script/backgroundrb stop
        /home/tacman/script/backgroundrb start
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo $"Usage: backgroundrb {start|stop|restart}"
        exit 1
esac