--- 
:backgroundrb: 
  :ip: 0.0.0.0
  :port: 11006
  #:environment: production

:development:
  :backgroundrb:
    :log: foreground # foreground mode,print log messages on console

:production:
  :backgroundrb:
    :debug_log: false # disable log workers and other logging 

:schedules:

  :hourly_worker:
    :hourly_tasks:
      :trigger_args: 0 30 * * * * *

  :nightly_worker:
    :nightly_tasks:
      :trigger_args: 0 0 0 * * * *


