--- 
:backgroundrb: 
  :ip: 0.0.0.0
  :port: 11006
  #:environment: production

:development:
  :backgroundrb:
    :log: foreground # foreground mode,print log messages on console

:production:
  :backgroundrb:
    :debug_log: false # disable log workers and other logging

:schedules:

  :hourly_worker:
    :hourly_tasks:
      :trigger_args: 0 2 * * * * *

  :daily_worker:
    :daily_tasks:
      :trigger_args: 0 1 3 * * * *

  :aaa_log_worker:
    :gather_aaa_logs:
      :trigger_args: 0 */5 * * * * *
